
package com.mycompany.practica1lenguajes.ventanaGrafica;

import com.mycompany.practica1lenguajes.Frame.NumeracionLinea;
import com.mycompany.practica1lenguajes.Token.Automata;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.DefaultHighlighter.DefaultHighlightPainter;
import javax.swing.text.Highlighter;

/**
 *
 * @author Melanni Tzul
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        NumeracionLinea NumeroLinea = new NumeracionLinea(AreaCargaArchivo);//Instanciar clase numeracionLinea y llamar al tesarea que es la carga de archivos
        jScrollPane1.setRowHeaderView(NumeroLinea);
        this.setLocationRelativeTo(null);// centrar ventana
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        CargarArchivoBoton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaCargaArchivo = new javax.swing.JTextArea();
        GuardarArchivojButton1 = new javax.swing.JButton();
        BuscarPalabrajButton1 = new javax.swing.JButton();
        BuscarPalabrajTextField1 = new javax.swing.JTextField();
        AnalizadorLexicojButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TransicionesjTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ReporteDeErroresjTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        ReporteDeTokensjTable2 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        RecuentoDeLexemasjTable4 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LimpiarjButton1 = new javax.swing.JButton();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador léxico.");

        CargarArchivoBoton.setText("Cargar Archivo");
        CargarArchivoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoBotonActionPerformed(evt);
            }
        });

        AreaCargaArchivo.setColumns(20);
        AreaCargaArchivo.setRows(5);
        jScrollPane1.setViewportView(AreaCargaArchivo);

        GuardarArchivojButton1.setText("Guardar Archivo");
        GuardarArchivojButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarArchivojButton1ActionPerformed(evt);
            }
        });

        BuscarPalabrajButton1.setText("Buscar palabra");
        BuscarPalabrajButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPalabrajButton1ActionPerformed(evt);
            }
        });

        AnalizadorLexicojButton1.setText("Analizador Lexico");
        AnalizadorLexicojButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalizadorLexicojButton1ActionPerformed(evt);
            }
        });

        TransicionesjTextArea.setColumns(20);
        TransicionesjTextArea.setRows(5);
        jScrollPane2.setViewportView(TransicionesjTextArea);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Movimientos del Autómata");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Reportes");

        ReporteDeErroresjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cadena de error", "Fila", "Columna"
            }
        ));
        jScrollPane3.setViewportView(ReporteDeErroresjTable1);

        ReporteDeTokensjTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Token", "Lexema", "Fila", "Columna"
            }
        ));
        jScrollPane4.setViewportView(ReporteDeTokensjTable2);

        RecuentoDeLexemasjTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Lexema", "Token", "Cantidad"
            }
        ));
        jScrollPane6.setViewportView(RecuentoDeLexemasjTable4);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Reporte de Tokens");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Recuento de Lexemas");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Reportes de Errores");

        LimpiarjButton1.setText("Borrar todo");
        LimpiarjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(BuscarPalabrajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BuscarPalabrajButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                .addGap(85, 85, 85))))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GuardarArchivojButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CargarArchivoBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AnalizadorLexicojButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(LimpiarjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarPalabrajTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarPalabrajButton1))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(5, 5, 5)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CargarArchivoBoton)
                                .addGap(18, 18, 18)
                                .addComponent(GuardarArchivojButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(LimpiarjButton1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AnalizadorLexicojButton1)
                                .addGap(137, 137, 137))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(82, Short.MAX_VALUE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Boton para cargar mi archivo 
    private void CargarArchivoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoBotonActionPerformed
         AreaCargaArchivo.setText("");//Limpiar el tex area
        JFileChooser ventanaCargaArchivo=new JFileChooser();//Creo mi objeto file chooser
         //Usamos un entero, el nombre de nuestro objeto JFileCooser
        
         int numero=ventanaCargaArchivo.showOpenDialog(this); //This significa que abrira la ventana encima de nuesta ventana principal
         if (numero==JFileChooser.APPROVE_OPTION){// condicione para que sea la opcion que si se guardo mi archivo
             String linea;//Creo una variable tipo String 
             File archivo=ventanaCargaArchivo.getSelectedFile();//Con el File leo archivo. Se crea un archivo y se guarda el archivo que seleccionamos getSelectefFile(obtener archivo seleccionado)
             try {
                 FileReader LeerArchivo=new FileReader(archivo);//Leemos el archivo seleccionado
                 //Para que escriba linea por linea, BufferedReader va leyendo linea por linea
                 BufferedReader TextoLeido=new BufferedReader(LeerArchivo);
                 //siclo me sirve para ir leyendo todo el archivo linea por linea                
                 while((linea=TextoLeido.readLine())!=null){
                 AreaCargaArchivo.append(linea+"\n");//Mostramos linea por linea en el tex area y usamos append para que se coloque una debajo de otra
                 }
                 
             } catch (FileNotFoundException ex) {
                 JOptionPane.showMessageDialog(null,"Error al cargar el archivo");
             } catch (IOException ex) {
                 JOptionPane.showMessageDialog(null,"Error al cargar el archivo");
             }
             
         
         
         }
         
    }//GEN-LAST:event_CargarArchivoBotonActionPerformed

    //Boton que me permite guardar mi archivo ya sea nuevo o editado
    private void GuardarArchivojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarArchivojButton1ActionPerformed
     JFileChooser guardar = new JFileChooser();
        if (guardar.showDialog(null, "Guardar") == JFileChooser.APPROVE_OPTION) {
            File archivo = guardar.getSelectedFile();
            if (archivo.getName().endsWith("txt")) {
                String NuevoDocumento = AreaCargaArchivo.getText();
                GuardarDocumento(archivo, NuevoDocumento);
            } else {
                JOptionPane.showMessageDialog(null, "Nombre de archivo incorrecto");
            }
        }    
    }//GEN-LAST:event_GuardarArchivojButton1ActionPerformed
        //Metodo para guardar el nuevo archivo y elegir donde guardar
    public void GuardarDocumento(File archivo, String documento) {

        try {
            FileOutputStream salida = new FileOutputStream(archivo);
            byte[] bytxt = documento.getBytes();
            salida.write(bytxt);
            JOptionPane.showMessageDialog(null, "Archivo Guardado con exito");
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Error al guardar archivo");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al guardar archivo");
        }
    }
    
    
    
    //Boton que me permite buscar una palabra de mi archivo cargado,ingresado, editado visible en mi texArea
    private void BuscarPalabrajButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPalabrajButton1ActionPerformed
        String PalabraBuscar=BuscarPalabrajTextField1.getText();        
        BuscadorDePalabra(AreaCargaArchivo, PalabraBuscar);
        
    }//GEN-LAST:event_BuscarPalabrajButton1ActionPerformed

    //Boton que me permite visualizar en el texArea los estados de transición y reportes de mi archivo a analizar 
    private void AnalizadorLexicojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalizadorLexicojButton1ActionPerformed
      
       
        if (!AreaCargaArchivo.getText().equals("")) {
             Automata ObjAutomata = new Automata(AreaCargaArchivo);
             ObjAutomata.DescomponerLineasPalabras();
             TransicionesjTextArea.setEditable(false);
             ObjAutomata.ImprimirReportes();
        }else{
        JOptionPane.showMessageDialog(null,"No se encontro un archivo para analizar");
        
        }
       
    }//GEN-LAST:event_AnalizadorLexicojButton1ActionPerformed

    private void LimpiarjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarjButton1ActionPerformed
        AreaCargaArchivo.setText("");//Limpiar el tex area
        TransicionesjTextArea.setText("");       
         ((DefaultTableModel)RecuentoDeLexemasjTable4.getModel()).setRowCount(0);
         ((DefaultTableModel)ReporteDeErroresjTable1.getModel()).setRowCount(0);
         ((DefaultTableModel)ReporteDeTokensjTable2.getModel()).setRowCount(0);
    }//GEN-LAST:event_LimpiarjButton1ActionPerformed
     
      //Funcion que me permite buscar la palabra y resaltar el texto   
     public void BuscadorDePalabra(JTextArea AreaCargaArchivo, String PalabraBuscar) {

        DefaultHighlighter.DefaultHighlightPainter ResaltadoAmarillo = new DefaultHighlightPainter(Color.YELLOW);//Resalta el texto de color amarillo
        Highlighter marcaTextos = AreaCargaArchivo.getHighlighter();//Permite poder tener el  metodo para indicar
        marcaTextos.removeAllHighlights();//Nos permite poder borramos todas las palabaras resaltadas

        String contenido = AreaCargaArchivo.getText();//contenido del textarea
        int inicioDePalabra = 0;
        String palabraAComparar = "";
        for (int x = 0; x < contenido.length(); x++) {//este for explora hasta la ultima letra de la cadena
            if (contenido.charAt(x) == ' ' || contenido.charAt(x) == '\n') {//si es espacio o enter entonces hasta aqui se forma una palabra                                                                          
                //comparamos la palabra construida y la que se quiere buscar
                if (palabraAComparar.equals(PalabraBuscar)) {
                    try {
                        //si son iguales entonces usamos el inicio de la palabra y y la x para marcar el texto en esa posicion
                        marcaTextos.addHighlight(inicioDePalabra, x, ResaltadoAmarillo);
                    } catch (BadLocationException ex) {
                    }
                }
                palabraAComparar = "";//reiniciamos la paralbra referencia
                inicioDePalabra = x + 1;//el inicio de otra palabra sera la pocision despues de un enter o espacio
            } else {//si no hay espacio o enter entonces sumamos la letra a la palabra
                palabraAComparar = palabraAComparar + contenido.charAt(x);
                if (x == contenido.length() - 1) {//si estamos al final de la cadena
                    if (palabraAComparar.equals(PalabraBuscar)) {//y la palabra es igual a la a buscar entonces la marcamos
                        try {
                            marcaTextos.addHighlight(inicioDePalabra, (x + 1), ResaltadoAmarillo);
                        } catch (BadLocationException ex) {
                        }
                    }
                }
            }
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalizadorLexicojButton1;
    private javax.swing.JTextArea AreaCargaArchivo;
    private javax.swing.JButton BuscarPalabrajButton1;
    private javax.swing.JTextField BuscarPalabrajTextField1;
    private javax.swing.JButton CargarArchivoBoton;
    private javax.swing.JButton GuardarArchivojButton1;
    private javax.swing.JButton LimpiarjButton1;
    public static javax.swing.JTable RecuentoDeLexemasjTable4;
    public static javax.swing.JTable ReporteDeErroresjTable1;
    public static javax.swing.JTable ReporteDeTokensjTable2;
    public static javax.swing.JTextArea TransicionesjTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
